### ISSUE TITLE
[Umbrella] reason-urql v2 Refactors & Improvements

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/reason-urql#170]
This is a good and opportune moment to take some time to reflect on a couple of `reason-urql`-specific structures and APIs. Specifically, `reason-urql` is meant to be idiomatic Reason code, but some parts of the API have been tied to bindings and expose some of the disconnect between JS/TS and Reason.

Because we're preparing to land v2, this may be a good moment to:

- Improve APIs and make them more idiomatic and friendlier
- Clean up the project structure and reconcile some files
- Update APIs to use Reason idiomatic types as possible.

We can collect ideas in this umbrella issue and close it as soon as `v2` is released.

### Amount of Supporting Files

Currently the project is structured like a JS project with lots of files and some potentially confusing locations.

- The Client has its own folder and is segregated from its types, a separate types file exists
- The exchanges have their own folder with just one module
- Do we still need component support?
- The project's namespacing seems a little aggressive. Can we use BS namespaces better / more effectively?

### Hook Context APIs

A lot of the context is typed and directly accessible. It may make sense to extend the hook API to be more idiomatic for the GraphQL bindings, and to integrate more of the context into the hooks' arguments.

- Should the `request` be its own curried argument?
- Should `unit` be last in those hooks? We do have the required `request` argument.
- `partialOperationContext` could be integrated as a set of labelled optional arguments instead, right into the hook. We could write a small helper for that and pipe all arguments through. `requestPolicy` is duplicate for instance, `url` can be integrated, etc. Optimally the context itself should just be a JSON type and all relevant context options could be surfaced as labelled arguments.

### Other Exchange Bindings

We haven't bound to some crucial exchanges yet and this could be an opportunity to add them?

**Comment by parkerziegler** [comment]
Thanks for opening this @kitten! I'm going to separate each section above into a separate comment with thoughts and a checklist so folks we can discuss each piece by piece.

**Comment by parkerziegler** [comment]
### Amount of Supporting Files

I agree with you, we can certainly clean this up.

**The Client has its own folder and is segregated from its types, a separate types file exists**

I would be happy to move the client just beneath the top-level `src` directory and rejoin the contents of the `ClientTypes` module with it. The main reasons I separated it:

1. All of the `[@bs.deriving abstract]` auto-generated setters and getters were conflicting with one another, since we had several object structures to bind with similar names. This isn't as much of a problem anymore w/ record to object compilation. I probably overwrote some of these bindings too and could leave more types abstract.
2. It allowed the type of the `Client` module, `t`, to live in a separate module where both `Client` and `Exchanges` could reference it. `Client` uses the `Exchanges.t` type and `Exchanges` uses some of the operation types from `Client`. Woohoo, cyclic dependency! By moving certain types to a new file we could break the cycle. This can be solved by making `Exchanges` a sub-module of `Client`. Just a little harder to discover / parse perhaps.

I'm in support of this change overall!

- [ ] Flatten file structure to have `UrqlClient` and `UrqlExchanges` under `src`, potentially with `UrqlExchanges` as a sub-module of `UrqlClient`.

**Do we still need component support?**

I'd be down to deprecate! They just use the hooks anyways, and render prop APIs in Reason are just really pretty meh.

- [ ] Deprecate bindings for components.

**The project's namespacing seems a little aggressive. Can we use BS namespaces better / more effectively?**

Yeah, I'd like to do this too. I think what I have was mostly borne out of my earlier days writing Reason / BS code w/out namespacing and wanting to really make sure I wasn't conflicting with user-defined modules.

- [ ] Move to using BS namespaces more effectively.

Will write more when I get a break from client work tomorrow.

**Comment by parkerziegler** [comment]
## Hook Context APIs

**Should the request be its own curried argument?**
**Should unit be last in those hooks? We do have the required request argument.**

I think `unit` has to be last in order to support all arguments being labelled, no? Since otherwise Reason will curry the function and wait for further arguments to be applied rather than returning the `(state, execute)` tuple 🤔 Are you thinking we could do:

```reason
let (state, executeQuery) = useQuery(~pause=true, ~requestPolicy=`CacheAndNetwork, request);
```

where `request` is an unlabelled argument? Let me know your thoughts @kitten, the main reason the API stands where it does (final `unit` parameter) is to indicate the hook has been fully applied and shouldn't expect more arguments.

**partialOperationContext could be integrated as a set of labelled optional arguments instead, right into the hook. We could write a small helper for that and pipe all arguments through. requestPolicy is duplicate for instance, url can be integrated, etc. Optimally the context itself should just be a JSON type and all relevant context options could be surfaced as labelled arguments.**

I like this! The API I'm targeting:

```reason
let (state, executeQuery) = useQuery(
  ~request,
  ~requestPolicy=`CacheAndNetwork,
  ~url="https://localhost:3000/new-graphql-endpoint",
  ()
);

executeQuery(~requestPolicy=`NetworkOnly, ());
```

[X] Make options for modifying the operation context labelled arguments.
**Closed by #181**

**Comment by parkerziegler** [comment]
Alright, @kitten `v2` has been published! I believe I hit on most every issue here, so I'm going to close it. This release had a lot of good improvements in it and I didn't want to sit on them any longer 😅 I think next steps for us mostly include:

- Supporting next minor `urql` version.
- Beginning to outline bindings for exchanges and how we want to / don't want to support them. I'm mostly thinking about folder structure / moving to yarn workspaces, and ensuring that exchange versions and `urql` versions are compatible. Graphcache is definitely biggest on my list.
