### ISSUE TITLE
Add bindings for `Mutation` component.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/reason-urql#23]
This issue is very similar to #22, and should take a similar approach. Let's keep the code paths as convergent as possible between these components and hooks.

**Comment by parkerziegler** [comment]
### Roadmap

- [x] Add bindings for `Mutation` component.
- [x] Add example showing how to use the `Mutation` component.
- [ ] Add tests for the `Mutation` component.

**Comment by parkerziegler** [comment]
Closed by #29 and #30.
