### ISSUE TITLE
Add `examples` directory using yarn workspaces.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/reason-urql#28]
Similar to how `urql` has an `examples` directory (modeled loosely after Next's), we'll want to have some `examples` to demonstrate how to use `reason-urql` with ReasonReact. We should use yarn workspaces to manage dependencies across individual examples. Each should therefore have their own `package.json` and `bsconfig.json`. For the most part, all dependencies can be shared (`bs-platform`, `webpack`, `bs-css`, `reason-react`) and we'll take a `file:` dependency on `reason-urql`.

**Comment by parkerziegler** [comment]
### Roadmap

- [X] Add directory and setup yarn workspaces.
- [X] Add `reason-urql` as `file` dependency.
- [ ] Fix duplicated dependency issue caused by dependency on `reason-urql` 🤦‍♂️

**Comment by parkerziegler** [comment]
Closed by #29.
