### ISSUE TITLE
Add bindings for Exchanges.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/reason-urql#40]
Previously this issue was tracked in #26, but it's complex enough that I figured we'd make it a separate issue. We want `reason-urql` to add support for [exchanges](https://github.com/FormidableLabs/urql/blob/master/docs/basics.md). This shouldn't be too difficult, as `urql` already has a set of exchanges that are a part of the core API. We just need to expose those using `[@bs.module]` declarations. Adding exchange types will be a bit more complex and should be based off of the [`urql/types.ts` module](https://github.com/FormidableLabs/urql/blob/master/src/types.ts).

### Roadmap
- [x] Add bindings for exchange types.
- [x] Add support for shipped exchanges.
- [x] Add support and example for using some of the shipped exchanges.
- [x] Add support for custom exchanges. 
- [x] Add specific config for `subscriptionExchange`.

**Comment by parkerziegler** [comment]
Closed by #41 and #42.
