### ISSUE TITLE
Upgrade to latest version of Reason React.

### ISSUE THREAD

**Issue by kiraarghy** [FormidableLabs/reason-urql#45]
We should possibly think about a roadmap for this?

**Comment by parkerziegler** [comment]
For sure. I think I'd like to see your example land first, and I'm working on an example for the `subscriptionExchange`. Once we get those in, we can begin the latest `reason-react` upgrade alongside a move to `bs-platform@5.x.x`.

**Comment by kiraarghy** [comment]
Ace!

**Comment by parkerziegler** [comment]
I've got all of my examples in and running on `bs.platform@5.0.3`. Will make a switch to latest `ReasonReact` when I get back from PTO!

**Comment by jaredly** [comment]
I imagine this is a prereq for getting some of those wonderful hooks from urql 1.0?

**Comment by parkerziegler** [comment]
Yep! I have the conversion for `Mutation` working well w/ an updated example, and just need to bind the `useMutation` hook, so that'll be coming up in PR soon. If anyone wants to get started on restructuring `Query` / `Subscription` and binding `useQuery` / `useSubscription`, I'd love the help. It's a pretty easy conversion thanks to how nice the JSX 3 API is!

**Comment by parkerziegler** [comment]
All of the API docs also still use the JSX 2 syntax, so I'm hoping to update those in this process as well.

**Comment by parkerziegler** [comment]
### Roadmap

- [x] Bind `Provider` with new syntax.
- [ ] Bind `Query` with new syntax. Add `useQuery` hook.
- [x] Bind `Mutation` with new syntax. Add `useMutation` hook.
- [ ] Bind `Subscription` with new syntax. Add `useSubscription` hook.
- [ ] Update `Query` example.
- [x] Update `Mutation` example.
- [ ] Update `Subscription` example.
- [ ] Update and add docs.

**Comment by gugahoa** [comment]
Hi, @parkerziegler, I saw your commit that added support to useMutation, and binded Mutation and Provider with the new syntax.

Any reason not to write Mutation in terms of useMutation, instead of making a binding?

I was playing around yesterday trying to add support to useQuery, and that was the route I took. I wanted to know about this before making a PR to maintain consistency with other implementations.

**Comment by parkerziegler** [comment]
@gugahoa thanks for reaching out and starting to work on `useQuery`! The main reason I opted for that approach is to maintain these bindings as 1:1 with `urql`. `urql` currently is migrating to the components being powered under the hood by hooks: https://github.com/FormidableLabs/urql/pull/252, so effectively binding the components will do the achieve the same thing. Does that make sense? We are considering having `reason-urql` move towards more of its own thing down the line, but for a stable v1 I think we just want straightforward bindings with a little bit of extra syntax sugar.

**Comment by kiraarghy** [comment]
Going to have a look at useSubscription/Subscription to the new syntax.

**Comment by parkerziegler** [comment]
Last step to land this is to add better type inference bindings for `Subscription`, tracked in #77, and to add docs with the new APIs 🎉

**Comment by parkerziegler** [comment]
Hooks along with latest ReasonReact syntax have officially been released in `v1.0.0-beta.1` 🎉
